### ISSUE TITLE
Unable to execute script

### ISSUE THREAD

**Issue by roshanjonah** [mlavin/cloudping#7]
Hi there,

I am getting the following error for any URL:

{
  "stackTrace": [
    [
      "/var/task/cloudping.py",
      21,
      "ping",
      "timeout=options['timeout'])"
    ],
    [
      "/var/task/requests/api.py",
      53,
      "request",
      "return session.request(method=method, url=url, **kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      468,
      "request",
      "resp = self.send(prep, **send_kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      576,
      "send",
      "r = adapter.send(request, **kwargs)"
    ],
    [
      "/var/task/requests/adapters.py",
      437,
      "send",
      "raise ConnectionError(e, request=request)"
    ]
  ],
  "errorType": "ConnectionError",
  "errorMessage": "HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //www.janz.co/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f62791ed6d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))"
}

I am not sure what it is. 

Regards,
RJ

**Comment by mlavin** [comment]
Something looks off on how the script is configured. It's trying to reach the host `https` on the path `//www.janz.co/`. What is the JSON configuration that use used for configuring CloudWatch in this step https://github.com/mlavin/cloudping#cloudwatch?

**Comment by roshanjonah** [comment]
JSON for cloudwatch is as follows:
{"domain": "janz.co", "protocol": "http"}

Also tried the following with same error:
{"domain": "www.janz.co", "protocol": "http"}

**Comment by roshanjonah** [comment]
I just realised that since we have a redirect from HTTP to HTTPS automatically...it needs to be configured that way...so this worked:

{"domain": "janz.co", "protocol": "https"}

**Comment by mlavin** [comment]
Correct. It's currently configured to treat redirects as errors (for better or worse). I should probably make that more clear.
